# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
config.vm.define "HomeTask4" do |ht|
  ht.vm.hostname = "HomeTask4"
  ht.vm.box = "ubuntu/bionic64"
 ht.vm.box_check_update = false

ht.vm.network "forwarded_port", guest: 80, host: 8080
ht.vm.network "private_network", ip: "192.168.33.10"


config.vm.provider "virtualbox" do |vb|
  vb.name = "HomeTask4"
  vb.gui = true
  vb.memory = "1024"
 end

config.vm.provision "shell", inline: <<-SHELL
  apt-get update
   apt-get install -y apache2
   SHELL
end
end

#!/bin/bash

#Docker setup

sudo apt-get update
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
sudo apt-get update
apt-cache policy docker-engine
sudo apt-get install -y docker-engine
sudo systemctl status docker

sudo usermod -aG docker $ALina
